@baseUrl = http://127.0.0.1:8000

### Crear categoría
POST {{baseUrl}}/categorias/
Content-Type: application/json

{
  "nombre": "Tecnología",
  "descripcion": "Productos tecnológicos"
}

### Listar categorías
GET {{baseUrl}}/categorias/

### Crear producto
POST {{baseUrl}}/productos/
Content-Type: application/json

{
  "nombre": "Mouse Inalámbrico",
  "descripcion": "Mouse ergonómico bluetooth",
  "precio_base": "25999.99",
  "imagen_url": [
    "https://example.com/mouse-1.png",
    "https://example.com/mouse-2.png"
  ],
  "disponible": true
}

### Listar productos
GET {{baseUrl}}/productos/

### Obtener producto por id
GET {{baseUrl}}/productos/1

### Actualizar producto
PUT {{baseUrl}}/productos/1
Content-Type: application/json

{
  "nombre": "Mouse Inalámbrico Pro",
  "descripcion": "Mouse ergonómico bluetooth recargable",
  "precio_base": "31999.99",
  "imagen_url": ["https://example.com/mouse-pro.png"],
  "disponible": true
}